Traceback (most recent call last):
  File "./simtask.py", line 12, in <module>
    raise Exception( "Error case ! " )
Exception: Error case ! 
